-- Generated by opcode_vhdl_gen from opcodes.txt
library ieee;
library work;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.core_config.all;

package opcodes is

    constant OP_NOP: opcode := std_logic_vector(to_unsigned(0, OPCODE_LENGTH)); --
    constant OP_MOVA: opcode := std_logic_vector(to_unsigned(1, OPCODE_LENGTH)); --| const:12 | -- acc := const
    constant OP_MOVAR: opcode := std_logic_vector(to_unsigned(2, OPCODE_LENGTH)); --| ra:6 | -- acc := ra
    constant OP_MOVRA: opcode := std_logic_vector(to_unsigned(3, OPCODE_LENGTH)); --| ra:6 | -- ra := acc
    constant OP_MOVRR: opcode := std_logic_vector(to_unsigned(4, OPCODE_LENGTH)); --| ra:6 | rb:6 | -- ra := rb
    constant OP_LDA: opcode := std_logic_vector(to_unsigned(5, OPCODE_LENGTH)); --| const:12 | -- acc := *const
    constant OP_STA: opcode := std_logic_vector(to_unsigned(6, OPCODE_LENGTH)); --| const:12 | -- *const := acc
    constant OP_LDAR: opcode := std_logic_vector(to_unsigned(7, OPCODE_LENGTH)); --| ra:6 | -- acc := *ra
    constant OP_STAR: opcode := std_logic_vector(to_unsigned(8, OPCODE_LENGTH)); --| ra:6 | -- *ra := acc
    constant OP_LDR: opcode := std_logic_vector(to_unsigned(9, OPCODE_LENGTH)); --| ra:6 | rb:6 | -- ra := *rb
    constant OP_STR: opcode := std_logic_vector(to_unsigned(10, OPCODE_LENGTH)); --| ra:6 | rb:6 | -- *rb := ra
    constant OP_J: opcode := std_logic_vector(to_unsigned(11, OPCODE_LENGTH)); --| ra:6 | -- PC := ra
    constant OP_BEQ: opcode := std_logic_vector(to_unsigned(12, OPCODE_LENGTH)); --| ra:6 | rb:6 | -- if ra = acc: PC := rb
    constant OP_BNQ: opcode := std_logic_vector(to_unsigned(13, OPCODE_LENGTH)); --| ra:6 | rb:6 | -- if ra <> acc: PC := rb
    constant OP_ADD: opcode := std_logic_vector(to_unsigned(14, OPCODE_LENGTH)); --| ra:6 | -- acc = acc + ra
    constant OP_SUB: opcode := std_logic_vector(to_unsigned(15, OPCODE_LENGTH)); --| ra:6 | -- acc = acc - rb
    constant OP_MAC: opcode := std_logic_vector(to_unsigned(16, OPCODE_LENGTH)); --| ra:6 | rb:6 | -- acc = acc + ra * rb

end package opcodes;
