-- Generated by opcode_vhdl_gen from instruction_set.txt
library ieee;
library work;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.core_config.all;

package opcodes is

    constant OP_NOP: opcode := "000000";

    -- | const:12 | -- acc := const
    constant OP_MOVA: opcode := "000001";

    -- | ra:6 | -- acc := ra
    constant OP_MOVAR: opcode := "000010";

    -- | ra:6 | -- ra := acc
    constant OP_MOVRA: opcode := "000011";

    -- | ra:6 | rb:6 | -- ra := rb
    constant OP_MOVRR: opcode := "000100";

    -- | const:12 | -- acc := *const
    constant OP_LDA: opcode := "000101";

    -- | const:12 | -- *const := acc
    constant OP_STA: opcode := "000110";

    -- | -:6 | rb:6 | -- acc := *rb
    constant OP_LDAR: opcode := "000111";

    -- | -:6 | rb:6 | -- *rb := acc
    constant OP_STAR: opcode := "001000";

    -- | const:12 | -- acc := acc + const
    constant OP_ADDA: opcode := "001001";

    -- | const:12 | -- acc := acc - const
    constant OP_SUBA: opcode := "001010";

    -- | -:6 | rb:6 | -- acc := acc + rb
    constant OP_ADDAR: opcode := "001011";

    -- | -:6 | rb:6 | -- acc := acc - rb
    constant OP_SUBAR: opcode := "001100";

    -- | const:6 | rb:6 | -- rb := rb + const
    constant OP_ADDR: opcode := "001101";

    -- | const:6 | rb:6 | -- rb := rb - const
    constant OP_SUBR: opcode := "001110";

    -- | const:12 | -- pc := const
    constant OP_J: opcode := "001111";

    -- | -:6 | rb:6 | -- pc := rb
    constant OP_BR: opcode := "010000";

    -- | ra:6 | rb:6 | -- if rb = 0: pc := ra
    constant OP_BZ: opcode := "010001";

    -- | ra:6 | rb:6 | -- if rb != 0: pc := ra
    constant OP_BNZ: opcode := "010010";

    -- | ra:6 | rb:6 | -- acc := acc + ra * rb
    constant OP_MAC: opcode := "010011";

    -- | ra:6 | rb:6 | -- ra := *++rb
    constant OP_ILDR: opcode := "010100";

end package opcodes;
