-- Generated by opcode_vhdl_gen from instruction_set_example.txt
library ieee;
library work;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.core_config.all;

package opcodes is

    constant OP_NOP: opcode := "000000";

    -- | const:12 | -- acc := const
    constant OP_MOVA: opcode := "000001";

    -- | ra:6 | -- acc := ra
    constant OP_MOVAR: opcode := "000010";

    -- | ra:6 | -- ra := acc
    constant OP_MOVRA: opcode := "000011";

    -- | ra:6 | const:6 | -- ra := const
    constant OP_MOVR: opcode := "000100";

    -- | ra:6 | rb:6 | -- ra := rb
    constant OP_MOVRR: opcode := "000101";

    -- | ra:6 | rb:6 | -- rb := *ra
    constant OP_LDRR: opcode := "000110";

    -- | ra:6 | rb:6 | -- *ra := rb
    constant OP_STRR: opcode := "000111";

    -- | const:12 | -- acc := acc + const
    constant OP_ADDA: opcode := "001000";

    -- | -:6 | rb:6 | -- acc := acc + rb
    constant OP_ADDAR: opcode := "001001";

    -- | ra:6 | rb:6 | -- ra := ra + *rb
    constant OP_ADDRM: opcode := "001010";

    -- | ra:6 | rb:6 | -- ra := ra * *rb
    constant OP_MULRM: opcode := "001011";

    -- | -:12 | -- acc := p + (*coef++) * (*data++)
    constant OP_CMAC: opcode := "001100";

    -- | const:12 | -- pc := const
    constant OP_J: opcode := "001101";

    -- | -:6 | rb:6 | -- pc := rb
    constant OP_BR: opcode := "001110";

end package opcodes;
