# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "/opt/Xilinx/14.6/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "/home/nilewapp/project/sea-of-cpus/workspace/core/core.srcs/sources_1/ip/cg_lin_index_map.xml"

set cgProjectPath "/home/nilewapp/project/sea-of-cpus/workspace/core/core.srcs/sources_1/ip/blk_mem_gen_v7_3_0/coregen.cgc"

set ipFile "/home/nilewapp/project/sea-of-cpus/workspace/core/core.srcs/sources_1/ip/blk_mem_gen_v7_3_0/blk_mem_gen_v7_3_0.xco"

set ipName "blk_mem_gen_v7_3_0"

set vlnv "xilinx.com:ip:blk_mem_gen:7.3"

set cgPartSpec "xc6vlx240t-1ff1156"

set bomFilePath "/home/nilewapp/project/sea-of-cpus/workspace/core/core.srcs/sources_1/ip/blk_mem_gen_v7_3_0/pa_cg_bom.xml"

set hdlType "VHDL"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

# configure the IP
set result [source "/opt/Xilinx/14.6/ISE_DS/PlanAhead/scripts/pa_cg_config_core.tcl"]

exit $result

