#!/usr/bin/env python
import argparse
import os

def main():
    parser = argparse.ArgumentParser(prog = 'opcode_vhdl_gen')
    parser.add_argument('file')
    args = parser.parse_args()

    print("-- Generated by opcode_vhdl_gen from %s" % os.path.basename(args.file))

    print("""library ieee;
library work;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.core_interface.all;

package opcodes is
""")

    with open(args.file) as text:
        i = 0
        for line in text:
            words = line.split()
            mnemonic = words[0].upper()
            comment = " ".join(words[1:])
            print("    constant OP_%s: opcode := std_logic_vector(to_unsigned(%d, OPCODE_LENGTH)); --%s" % (mnemonic, i, comment))
            i = i + 1

    print("""
end package opcodes;""")

if __name__ == "__main__":
    main()
